33 suggest the minimum investment amount for reach the target allocation
leonardoarcari/dcapal pull request #141
Opened 2023-10-22 16:06 UTC by mattiapitossi

2023-10-23 17:57 UTC, corradopetrelli requested changes
Due cambiamenti e lato FE ci siamo dal mio punto di vista!

2023-10-23 17:57 UTC, corradopetrelli commented on dcapal-frontend/src/components/allocationFlow/investStep.js
> +  ACLASS,
unused

2023-10-23 17:57 UTC, corradopetrelli commented on dcapal-frontend/src/components/allocationFlow/investStep.js
> +};
Refactoring

```suggestion
const buildProblemInput = (assets, useWholeShares) => {
    return Object.values(assets).reduce(
      (as, a) => ({
        ...as,
        [a.symbol]: {
          // Common input
          symbol: a.symbol,
          target_weight: a.targetWeight / 100,
          // Use whole shares input
          ...(useWholeShares && {shares: a.qty}),
          ...(useWholeShares && {price: a.price}),
          ...(useWholeShares && {is_whole_shares: isWholeShares(a.aclass)}),
          // Use partial shares input
          ...(!useWholeShares && {current_amount: a.amount}),
        },
      }),
      {}
    );
};
```

2023-10-29 09:28 UTC, leonardoarcari requested changes

2023-10-29 09:28 UTC, leonardoarcari commented on dcapal-frontend/src/components/allocationFlow/investStep.js
> +            quoteCcy: String(quoteCcy),
Can we add `uppercase` to `className` for `quoteCcy` to make it all caps? Like here: https://github.com/leonardoarcari/dcapal/blob/master/dcapal-frontend/src/components/allocationFlow/portfolioStep/index.js#L234

2023-10-29 09:28 UTC, leonardoarcari commented on dcapal-frontend/src/workers/analyzer.js
> +  if (isSuggestionRequested) {
Is this still needed if we always pass `isSuggestionRequest === true`?

2023-10-29 09:37 UTC, leonardoarcari requested changes

2023-10-29 09:37 UTC, leonardoarcari commented on dcapal-frontend/src/components/allocationFlow/investStep.js
> +              : "investStep.youAlreadyReachedTargetAllocation"
Can we add a placeholder text while we wait for the suggestion to be available? It's weird that we move from "Already reached target allocation" to the "you should allocate X".

It can be a conditional render on `solution === null && isLoading`.

2023-10-29 09:37 UTC, leonardoarcari commented on dcapal-frontend/src/components/allocationFlow/investStep.js
> +      const [sol] = await Promise.all([launchSolver(), timeout(1000)]);
I think we can get rid of the `timeout(1000)` here. Better to get the suggested amount to invest as soon as it's ready, what do you think?

2023-10-29 16:57 UTC, mattiapitossi commented on dcapal-frontend/src/workers/analyzer.js
> +  if (isSuggestionRequested) {
Thanks for spotting this, yes, this was a simple test and then I forgot to remove it! Fixing now.

2023-10-29 17:00 UTC, mattiapitossi commented on dcapal-frontend/src/components/allocationFlow/investStep.js
> +      const [sol] = await Promise.all([launchSolver(), timeout(1000)]);
I agree, removing it now.

2023-10-29 17:19 UTC, mattiapitossi commented on dcapal-frontend/src/components/allocationFlow/investStep.js
> +              : "investStep.youAlreadyReachedTargetAllocation"
Definitely needed, thanks!

2023-11-01 17:34 UTC, leonardoarcari approved these changes
LGTM! Happy to merge anytime 🙂

2023-11-02 20:15 UTC, corradopetrelli requested changes
Only a small suggestion!

2023-11-02 20:15 UTC, corradopetrelli commented on dcapal-frontend/src/components/allocationFlow/investStep.js
> +import { replacer, timeout } from "../../utils";
`timeout` is unused

```suggestion
import { replacer } from "../../utils";
```

2023-11-04 10:05 UTC, corradopetrelli approved these changes

2023-11-04 10:05 UTC, merged