Multiple portfolios support
leonardoarcari/dcapal pull request #156
Opened 2023-11-04 11:43 UTC by leonardoarcari

## Pull request details

- [ ] Transform `portfolioSlice` to allow multiple portfolios
- [ ] Modify state consumers to offer same behavior as today
- [ ] Introduce new UI to manage multiple portfolios

## Breaking changes

- No breaking changes. Portfolio importer will be updated to support old and new exported portfolios.

## Issues fixed

1. Closes #154 

## Other relevant information

x

2023-11-09 17:54 UTC, corradopetrelli requested changes

2023-11-09 17:54 UTC, corradopetrelli commented on dcapal-frontend/src/utils/index.js
> +import { v4 as uuidv4 } from "uuid";
Why is used uuid?

Node 18 is used so crypto can be used (available from node 14). If you want you can delete a uuid dependency from package.json.

```
const { randomUUID } = require('crypto');
```

2023-11-09 17:54 UTC, corradopetrelli commented on dcapal-frontend/src/utils/index.js
> +};
is it necessary?

2023-11-09 17:54 UTC, corradopetrelli commented on dcapal-frontend/src/components/allocationFlow/importStep.js
> +  imported.name = pfolio.name || "Main portfolio";
Translate default value "Main portfolio"

2023-11-09 17:54 UTC, corradopetrelli commented on dcapal-frontend/src/components/allocationFlow/portfolioStep/portfolioSlice.js
> +      pfolio.totalAmount = pfolio.totalAmount;
can it be removed or is there a reason?

2023-11-09 17:54 UTC, corradopetrelli commented on dcapal-frontend/src/app/store.js
> +    const name = "Main portfolio";
Translate default

2023-11-09 17:54 UTC, corradopetrelli commented on dcapal-frontend/src/components/allocationFlow/importStep.js
> +
You can assign directly IIFE return value to `imported.fees`

2023-11-09 17:58 UTC, leonardoarcari commented on dcapal-frontend/src/utils/index.js
> +import { v4 as uuidv4 } from "uuid";
Are you sure? That code is running in the browser, how can I access Node.js modules?

2023-11-09 18:00 UTC, leonardoarcari commented on dcapal-frontend/src/utils/index.js
> +};
Generated `uuid` is hyphenated. I don't like it but probably it's better to keep it leaner?

2023-11-09 18:14 UTC, corradopetrelli commented on dcapal-frontend/src/utils/index.js
> +import { v4 as uuidv4 } from "uuid";
Yes. To remove any doubt. Run in your browser:
```window.crypto.randomUUID()```

(maybe require crypto it is unnecessary because it is a read-only global object).

2023-11-09 18:16 UTC, corradopetrelli commented on dcapal-frontend/src/utils/index.js
> +};
For me there are no problem to maintain this (local) notation, I just wanted to know why the hyphens were removed

2023-11-09 18:17 UTC, corradopetrelli commented on dcapal-frontend/src/components/allocationFlow/importStep.js
> +
Github didn't select the other lines for me but I'm referring to the IIFE above this line of code

2023-11-09 18:32 UTC, leonardoarcari commented on dcapal-frontend/src/utils/index.js
> +import { v4 as uuidv4 } from "uuid";
Today I Learnt 🙂 Thanks! Fixed

2023-11-09 18:33 UTC, leonardoarcari commented on dcapal-frontend/src/utils/index.js
> +};
On a second thought, I agree with you. Better to stay consistent. Fixed.

2023-11-09 18:33 UTC, leonardoarcari commented on dcapal-frontend/src/components/allocationFlow/portfolioStep/portfolioSlice.js
> +      pfolio.totalAmount = pfolio.totalAmount;
No reason, tbh I don't know why it was there. Removed.

2023-11-09 18:34 UTC, leonardoarcari commented on dcapal-frontend/src/components/allocationFlow/importStep.js
> +
Good point! Fixed.

2023-11-11 07:48 UTC, mattiapitossi approved these changes

2023-11-11 11:28 UTC, corradopetrelli approved these changes
Great work! 🚀

2023-11-11 11:52 UTC, merged