Multiple portfolios UI
leonardoarcari/dcapal pull request #177
Opened 2023-11-20 14:40 UTC by leonardoarcari

## Pull request details

_TBD_

## Breaking changes

_TBD_

## Issues fixed

1. #154

2023-11-21 18:20 UTC, corradopetrelli requested changes

2023-11-21 18:20 UTC, corradopetrelli commented on dcapal-frontend/public/locales/en/translation.json
> +      "discard": "Discard",
It is never used, you can delete it.

```suggestion
```

2023-11-21 18:20 UTC, corradopetrelli commented on dcapal-frontend/public/locales/it/translation.json
> +      "discard": "Cancella",
It is never used, you can delete it.

```suggestion
```

2023-11-21 18:20 UTC, corradopetrelli commented on dcapal-frontend/src/components/allocationFlow/steps/importFile.js
> -    dispatch(clearPortfolio({}));
It called only here. Valutate to delete from codebase `clearPortfolio` (`deletePortfolio` is its substitute)

2023-11-21 18:20 UTC, corradopetrelli commented on dcapal-frontend/src/components/allocationFlow/steps/portfolios/index.js
> +  return a - b;
Why `a-b`? It is risky, it is a difference between 2 strings

It is difficult to happen but for instance:
```javascript
sortCcy(NaN, NaN) // NaN
sortCcy('USD', 'EUR') // NaN
```

For second case convert `a` and `b` to lower case before destructuring

2023-11-21 18:27 UTC, leonardoarcari commented on dcapal-frontend/src/components/allocationFlow/steps/portfolios/index.js
> +  return a - b;
Not 100% sure I got your point 🤔 I'm not sorting lexicographically but by currency priority (which is an integer) as defined in https://github.com/leonardoarcari/dcapal/pull/177/files#diff-b8bdfc73ca89a6ff767fa415501bc293cba9550fe144241ae8f967bc498158b5R88

2023-11-22 08:10 UTC, corradopetrelli commented on dcapal-frontend/src/components/allocationFlow/steps/portfolios/index.js
> +  return a - b;
Ok, it's clear, so my example cannot appear in our context

2023-11-22 14:42 UTC, leonardoarcari commented on dcapal-frontend/src/components/allocationFlow/steps/importFile.js
> -    dispatch(clearPortfolio({}));
I agree. Removed `clearPortfolio` reducer

2023-11-22 19:30 UTC, corradopetrelli approved these changes

2023-11-22 19:50 UTC, merged