Add `/import/portfolio` endpoint to enable integration with third-party tools
leonardoarcari/dcapal pull request #194
Opened 2023-11-23 17:21 UTC by leonardoarcari

## Pull request details

TBD 

## Breaking changes

_None_

## Issues fixed

1. #34 

## Other relevant information

_TBD_

2023-11-25 21:09 UTC, KristianLentino99 commented on dcapal-frontend/src/routes/importPage.js
> +    const fetchPortfolio = async () => {
I would think about moving this kind of business logic inside a `useImportPortfolio` hook so that we can better reuse the code if this is needed in other part, what do you think?

2023-11-25 21:10 UTC, KristianLentino99 commented on dcapal-frontend/src/routes/importPage.js
> +const fetchImportedPortfolio = async (id) => {
I would move all the `import` related logic into a hook or something similar we can better reuse

2023-11-25 21:24 UTC, leonardoarcari commented on dcapal-frontend/src/routes/importPage.js
> +    const fetchPortfolio = async () => {
Oh very interesting suggestion! I've never written a custom hook myself but from a quick look [here](https://react.dev/learn/reusing-logic-with-custom-hooks), it looks like a super clean way to fetch the portfolio.

2023-11-25 21:33 UTC, KristianLentino99 commented
## Cancel should redirect to homepage from import functionality
If I click the import portfolio, select the json file I'm redirected correctly to the allocate step. If I click the "cancel" button here I'm getting redirected to the currency step at the moment. I understand that it's the same step of the manual flow, but I would consider to differentiate the behaviour depending where the user came from. If the user came from the import portfolio functionality I would expect to be redirected to the homepage (maybe I've choosen the wrong JSON and I want to re-import the correct one).


What do you think?

2023-11-25 21:34 UTC, KristianLentino99 commented on dcapal-frontend/src/routes/importPage.js
> +    const fetchPortfolio = async () => {
Yeah absolutely, we can use the hooks to keep correctly segregated the logics behind the "import" functionality, but maybe @corradopetrelli is the right guy for this.

2023-11-25 21:36 UTC, KristianLentino99 commented on dcapal-frontend/src/components/allocationFlow/steps/importFile.js
>  const parseFees = (fees) => {
I would move this parse utility together with the other logics behind the import so that the `importFile.js` contains only presentation related code (as much as possible)

2023-11-25 21:44 UTC, leonardoarcari commented
> ## Cancel should redirect to homepage from import functionality
> If I click the import portfolio, select the json file I'm redirected correctly to the allocate step. If I click the "cancel" button here I'm getting redirected to the currency step at the moment. I understand that it's the same step of the manual flow, but I would consider to differentiate the behaviour depending where the user came from. If the user came from the import portfolio functionality I would expect to be redirected to the homepage (maybe I've choosen the wrong JSON and I want to re-import the correct one).
> 
> What do you think?

@KristianLentino99 Where are you experiencing that behavior? Current stable? I'm asking because after #177 got merged, allocate step brings you back to the _My Portfolios_ page, which superseded the currency step. Maybe you can attach a quick video? Thanks!

2023-11-25 21:56 UTC, KristianLentino99 commented
> > ## Cancel should redirect to homepage from import functionality
> > If I click the import portfolio, select the json file I'm redirected correctly to the allocate step. If I click the "cancel" button here I'm getting redirected to the currency step at the moment. I understand that it's the same step of the manual flow, but I would consider to differentiate the behaviour depending where the user came from. If the user came from the import portfolio functionality I would expect to be redirected to the homepage (maybe I've choosen the wrong JSON and I want to re-import the correct one).
> > What do you think?
> 
> @KristianLentino99 Where are you experiencing that behavior? Current stable? I'm asking because after #177 got merged, allocate step brings you back to the _My Portfolios_ page, which superseded the currency step. Maybe you can attach a quick video? Thanks!

Oh yeah sorry, but still in my opinion if as a user I click "back" button coming from the new import functionality I would expected to come back to the homapeg to retry to import a new file. Maybe I'm just biased. 


https://github.com/leonardoarcari/dcapal/assets/60007558/91af46c8-d170-4048-a382-690b5ed5d085

2023-11-25 21:59 UTC, KristianLentino99 commented
If I import two times a file without a name I get two "Portafoglio principale", in my opinion could be a little misleading and we can add a number maybe to make the user understand which is the older (and so he can delete it).

2023-11-26 17:15 UTC, leonardoarcari commented on dcapal-frontend/src/routes/importPage.js
> +    const fetchPortfolio = async () => {
Done, please checkout new `useFetchImportedPortfolio.js` hook

2023-11-26 17:15 UTC, leonardoarcari commented on dcapal-frontend/src/routes/importPage.js
> +const fetchImportedPortfolio = async (id) => {
Done, moved to `useFetchImportedPortfolio.js`

2023-11-26 17:17 UTC, leonardoarcari commented on dcapal-frontend/src/components/allocationFlow/steps/importFile.js
>  const parseFees = (fees) => {
Makes sense! Moved to `portfolioSlice.js` where we already had some `FeeType` parsing

2023-11-26 17:17 UTC, leonardoarcari commented
> If I import two times a file without a name I get two "Portafoglio principale", in my opinion could be a little misleading and we can add a number maybe to make the user understand which is the older (and so he can delete it).

@KristianLentino99 Very good point, I agree. Took me a while, but made it work 😄 Can you give it a try? Thanks!

2023-11-26 17:28 UTC, KristianLentino99 commented on dcapal-frontend/src/routes/importPage.js
> +    const fetchPortfolio = async () => {
Looks great to me!

2023-11-26 17:30 UTC, KristianLentino99 commented
@leonardoarcari the increment of the portfolio count looks great!

2023-12-04 17:43 UTC, corradopetrelli requested changes
According to me it's necessary to check asset name from provider (or avoid it required) because as Asset name I can add whatever I want.

For instance:
![image](https://github.com/leonardoarcari/dcapal/assets/36475130/cdd6554e-f7ba-42f3-8daa-a08a881f4ddc)

2023-12-08 15:27 UTC, merged