Fix issue reported in 205
leonardoarcari/dcapal pull request #216
Opened 2023-12-09 13:46 UTC by mattiapitossi

## Pull request details

X

## Breaking changes

X

## Issues fixed

1. X
2. X
3. X

## Other relevant information

X

2023-12-09 13:55 UTC, leonardoarcari requested changes
I think we should also add `useWholeShares` to the `useEffect` dependency list in order to trigger suggestion refresh on **Use fractional shares** toggle

2023-12-09 13:55 UTC, leonardoarcari commented on dcapal-frontend/src/components/allocationFlow/steps/invest.js
> +        is_whole_shares: isWholeShares(a.aclass),
Is it this correct? If users select **Use fractional shares** it should set `is_whole_shares` always to `true`, even for EQUITY asset class

2023-12-09 14:11 UTC, mattiapitossi commented on dcapal-frontend/src/components/allocationFlow/steps/invest.js
> +        is_whole_shares: isWholeShares(a.aclass),
is_whole_shares is not used by the suggestion algorithm, so we can just pass whatever comes with the asset and nothing will change. I can change this to `a.is_whole_shares ` in case we need this in the future, what do you think?

2023-12-10 13:44 UTC, leonardoarcari requested changes

2023-12-10 13:44 UTC, leonardoarcari commented on dcapal-frontend/src/components/allocationFlow/steps/invest.js
> +        is_whole_shares: a.is_whole_shares,
Are you sure about this? IIRC, there's no `is_whole_shares` field in the `asset` object. The way you implemented it before was right:
```suggestion
        is_whole_shares: isWholeShares(a.aclass),
```

2023-12-10 13:45 UTC, leonardoarcari commented on dcapal-frontend/src/components/allocationFlow/steps/invest.js
> +        is_whole_shares: isWholeShares(a.aclass),
Oh I wasn't aware of that. I though you'd take into account whether an asset was fractional or not in your algorithm. Never mind then, your implementation is right, thanks!

2023-12-10 14:15 UTC, leonardoarcari approved these changes

2023-12-10 14:55 UTC, merged