[New translation] Italian Language
leonardoarcari/dcapal pull request #56
Opened 2023-09-10 12:06 UTC by corradopetrelli

## Pull request details

* Introduced library for translating
* Introduce italian language
* Introduce language detector

## Breaking changes

Nothing

## Issues fixed

1. #55

## Other relevant information
![image](https://github.com/corradopetrelli/dcapal/assets/36475130/cc67ce29-ad1e-4feb-84dc-3bb8734f1946)

2023-09-10 12:14 UTC, corradopetrelli commented
@leonardoarcari I kindly ask you to check if all the translations are correct in your opinion

2023-09-11 11:43 UTC, corradopetrelli commented
> Kind request: any chance you could add a language picker too? I'd like to have a way to switch between translations. We could store chosen locale in the app store (appSlice.js), while defaulting to browser's language if nothing's set.

Currently I used the `LanguageDetector` provided by the library to select language (in case of language not found set to English).
When I have time I will add this feature in this PR.

2023-09-11 19:28 UTC, leonardoarcari commented
> Hey @leonardoarcari, what do you think?

Thanks! Think it's good enough for the first iteration 👍 Could you please move it to the very bottom of the menu in the mobile view? Something like `justify-self-end`

2023-09-11 20:10 UTC, leonardoarcari requested changes

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "discard": "Scarta"
Cancella

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "getStarted": "Inizia",
Inizia qui

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "about": "Informazioni",
Chi siamo

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "chooseCurrency": "Scegli la tua valuta per il portafoglio"
Seleziona la valuta del tuo portafoglio

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "leftBudget": "Questo è il tuo budget residuo. Riservalo per la prossima visita su DcaPal",
Questo è il tuo budget residuo. Tienilo per la prossima volta che vieni su DcaPal

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "nothingToTradeHold": "Niente da negoziare. Tieni semplicemente",
Nulla da scambiare. Tieni e basta.

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "nothingToTradeHodl": "Niente da negoziare. Tieni semplicemente",
Nulla da scambiare. HODL!

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "budgetAllocated": "Attendi! Stiamo allocando il tuo budget",
Un momento. Stiamo allocando il tuo budget

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "allocationReady": "Grande successo! La tua allocazione è pronta",
Fatto! La tua allocazione è pronta

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "transactionFees": "Commissioni di transazione"
Costi di transazione

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "transactionFees": "Commissioni di transazione",
Costi di transazione

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "fromFile": "dal file"
da file

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "taxEfficientInfo": "Con l'opzione <0>{{tax}}</0>, facciamo del nostro meglio per riequilibrare il tuo portafoglio utilizzando la tua liquidità, con suggerimenti solo per l'acquisto. In caso co
Con l'opzione <0>{{tax}}</0>, facciamo del nostro meglio per ribilanciare il tuo portafoglio utilizzando la tua liquidità, solo con suggerimenti di acquisto. Altrimenti, potremmo suggerire di vendere parte delle tue posizioni.

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "doNotSplitInfo": "Con l'opzione <0>{{message}}</0>, suggeriamo il numero di azioni da acquistare o vendere per asset non frazionari come azioni o ETF. In caso contrario, potremmo suggerire qua
Con l'opzione <0>{{message}}</0>, suggeriamo il numero di azioni da acquistare o vendere per asset non frazionari come azioni o ETF. In caso contrario, potremmo suggerire importi teoricamente ottimali da acquistare o vendere, ma dovrai calcolare tu quante unità acquistare.

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "wholeShares": "azioni intere",
unità

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +      "about": "Informazioni"
Chi siamo

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +        "presentation2": "Ho progettato DcaPal come uno strumento <0>{{tool}}</0> per gli investitori passivi come me: persone finanziariamente istruite che gestiscono i propri portafogli con un nume
Ho progettato DcaPal come uno <0>{{tool}}</0> per investitori passivi come me: persone con una cultura finanziaria che gestiscono il proprio portafoglio in autonomia, investendo in asset che replicano i principali indici mondiali.

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +        "commonProblem": "Mi trovavo di fronte a un problema comune: è quel momento del mese, ho dei risparmi da investire e devo suddividerli tra i miei asset nel portafoglio.",
Mi trovavo di fronte a un problema comune: è quel giorno del mese, ho dei risparmi da investire e devo suddividerli tra i miei asset in portafoglio

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +        "motivation": "Ecco perché c'è DcaPal. Vieni qui ogni settimana/mese/trimestre, costruisci il tuo portafoglio, definisci l'allocazione degli asset in percentuale, inserisci quanto vuoi invest
Ecco perché c'è DcaPal. Vieni qui ogni settimana/mese/trimestre, costruisci il tuo portafoglio, definisci la tua allocazione ideale, inserisci quanto vuoi investire e <0>{{algorithm}}</0>

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +        "letTheAlgorithmDoTheSplittingForYou": "lascia che l'algoritmo faccia la suddivisione per te",
lascia che l'algoritmo faccia i calcoli per te

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +        "exportPortfolio": "Puoi anche esportare il tuo portafoglio e importarlo la prossima volta per risparmiare preziosi minuti.",
Puoi anche esportare il tuo portafoglio e importarlo la prossima volta per risparmiare tempo prezioso.

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +        "privacyPolicyMessage1": "Ecco la nostra povera politica sulla privacy. Conserviamo la tua posizione IP per scopi statistici. Questo è tutto. Niente di più.",
Ecco la nostra politica sulla privacy da barboni. Conserviamo il tuo indirizzo IP per scopi statistici. Basta. Niente di più.

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +        "privacyPolicyMessage2": "Poiché DcaPal è un servizio senza accesso, non effettuiamo il tracciamento degli utenti. Non conserviamo dati degli utenti: asset del portafoglio, importi investiti,
Poiché DcaPal è un servizio senza registrazione, non effettuiamo il tracciamento degli utenti. Non conserviamo dati degli utenti: asset del portafoglio, importi investiti, niente esce mai dal tuo browser.

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +        "title1": "Dollar Cost Averaging reso facile",
Il Piano d'Accumulo reso facile

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +        "subtitle1": "DcaPal ti aiuta a mantenere il controllo del tuo portafoglio con suggerimenti fiscali efficienti per i tuoi investimenti mensili.",
DcaPal ti aiuta a tenere il tuo portafoglio sotto controllo con suggerimenti fiscalmente efficienti per i tuoi investimenti mensili

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +        "subtitle2": "<p1>Mantenere il tuo portafoglio equilibrato è difficile. <it>Noi sappiamo com'è</it>.</p1><p2>Fai l'allocazione degli asset il primo giorno, il mercato sale e scende e ti perdi
<p1>Mantenere il tuo portafoglio bilanciato è difficile. <it>Sappiamo com'è la storia</it>.</p1><p2>Imposti la tua asset allocation il giorno uno, il mercato sale e scende e finisce che non sai più come suddividere i tuoi risparmi mensili.</p2><p3>Ci pensa DcaPal.</p3>

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +        "cardStep2": "<p1>Dicci <bold>il tuo budget</bold> per questo mese</p1>",
<p1>Inserisci <bold>il tuo budget</bold> per questo mese</p1>

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/public/locales/it/translation.json
> +        "getStart": "<p1>Inizia ora. È gratuito!</p1><p2>Abbiamo creato DcaPal come uno strumento rapido per gli investitori passivi. Ottieni la tua allocazione in pochi minuti.</p2><p3>Non è richies
<p1>Inizia ora. È gratuito!</p1><p2>Abbiamo creato DcaPal come uno strumento rapido per gli investitori passivi. Alloca il tuo budget in pochi minuti.</p2><p3>Non è richiesta alcuna registrazione!</p3>

2023-09-11 20:10 UTC, leonardoarcari commented on dcapal-frontend/src/components/languageSwitcher.js
> +      value={useSelector((state) => state.app.language)}
Can we allow `state.app.language` to be `null` and if so, default to? 
```js
const {t, i18n} = useTranslation();

i18n.language
```

Otherwise, users by default would start from English language, while they should start from browser language if they don't interact with `LanguageSwitcher`.

2023-09-12 15:03 UTC, mattiapitossi commented on dcapal-frontend/public/locales/it/translation.json
> +      "budgetAllocated": "Attendi! Stiamo allocando il tuo budget",
Would it make sense to use "Attenti un momento, stiamo allocando il tuo budget"?

2023-09-12 15:06 UTC, mattiapitossi commented on dcapal-frontend/public/locales/it/translation.json
> +      "targetWeight": "Peso Obiettivo",
Not sure about this, what about "Allocazione target"?

2023-09-12 15:10 UTC, mattiapitossi commented on dcapal-frontend/public/locales/it/translation.json
> +      "reviewYourWeight": "Rivedi i tuoi <0>{{targetWeights}}</0>. Devono sommare al 100% (attualmente <1>{{actualWeight}} %</1>)",
```suggestion
      "reviewYourWeight": "Rivedi i tuoi <0>{{targetWeights}}</0>. La somma deve essere pari al 100% (attualmente <1>{{actualWeight}} %</1>)",
```

2023-09-12 16:16 UTC, corradopetrelli commented on dcapal-frontend/public/locales/it/translation.json
> +      "targetWeight": "Peso Obiettivo",
Damn, I've forgotten Italian by now hahaha
Thanks!

2023-09-12 17:11 UTC, corradopetrelli commented
@leonardoarcari 
* I use `i18n.resolvedLanguage`, it returns `it` instead of `it-IT`
* What do you think?
<p align="center">
<img src="https://github.com/leonardoarcari/dcapal/assets/36475130/3426af26-3516-4133-b9c8-c7ee6eb98e30"  height="500">
</p>

@mattiapitossi thank you so much, I add you as co-author of the commit 056a239d72261ea266e64680c7682f473d10c82d

2023-09-12 17:16 UTC, leonardoarcari commented
> @leonardoarcari 
> * I use `i18n.resolvedLanguage`, it returns `it` instead of `it-IT`
> * What do you think?

Good stuff! Looks good to me thanks! 💪

2023-09-16 09:12 UTC, leonardoarcari approved these changes
LGTM. Ready to ship! 🚢

2023-09-16 09:23 UTC, merged